apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # 名字必需与下面的 spec group字段匹配，并且格式为 '<名称的复数形式>.<组名>'
  name: clusterconfigs.api.practice.com
  labels:
    version: "0.1"
spec:
  group: api.practice.com
  versions:
    - name: v1alpha1
      # 是否有效
      served: true
      #是否是存储版本
      storage: true
      # kubectl get clusterconfig 显示的字段
      additionalPrinterColumns:
        - name: NamespaceList
          type: string
          jsonPath: .status.processedNamespace
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          # 没有任何内容会被修剪，哪怕不被识别
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
  names:
    # 复数名
    plural: clusterconfigs
    # 单数名
    singular: clusterconfig
    kind: ClusterConfig
    listKind: ClusterConfigList
    # kind的简称，就像service的简称是svc
    shortNames:
      - cc
  scope: Namespaced