apiVersion: api.practice.com/v1alpha1
kind: ClusterConfig
metadata:
  name: cluster-config-configmaps
  namespace: default
spec:
  configType: configmaps
  namespaceList: default,test
  data:
    # 类属性键；每一个键都映射到一个简单的值
    player_initial_lives: "3"
    ui_properties_file_name: "user-interface.properties"
    # 类文件键
    game.properties: |
      enemy.types=aliens,monsters
      player.maximum-lives=5
    user-interface.properties: |
      color.good=purple
      color.bad=yellow
      allow.textmode=true    
    
